# Generated by Django 2.2.7 on 2020-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='cached',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
