# Generated by Django 2.2.7 on 2020-01-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20200114_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='error_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='response_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='cached',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
