# Generated by Django 2.2.7 on 2020-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20200114_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='http_version',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
