# Generated by Django 2.2.7 on 2020-01-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_analysis_http_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='page_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
