# Generated by Django 2.2.7 on 2020-01-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_analysis_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UNSET', 'Links type not set.'), ('INTERNAL', 'Internal links'), ('EXTERNAL', 'External links')], default='UNSET', max_length=30)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('inaccessible_count', models.IntegerField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='analyzer.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='analyzer.Analysis')),
            ],
        ),
    ]
