# Generated by Django 2.2.7 on 2020-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_analysis_is_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='cached',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='error_description',
            field=models.CharField(default='n/a', max_length=300),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='http_version',
            field=models.CharField(blank=True, default='n/a', max_length=5),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='page_title',
            field=models.CharField(blank=True, default='n/a', max_length=300),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='response_code',
            field=models.CharField(default='n/a', max_length=5),
        ),
    ]
