# Generated by Django 2.2.7 on 2020-01-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_auto_20200115_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='type',
            new_name='link_type',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='error_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='http_version',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='page_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='response_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='heading',
            name='count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='link',
            name='count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='inaccessible_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
