# Generated by Django 2.2.7 on 2020-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_auto_20200116_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('UNSET', 'Tag type not set.'), ('HEADINGS', 'Headings')], default='UNSET', max_length=30),
        ),
    ]
